package internal

const SfAny = "anytype"
const SfBase64 = "base64"
const SfBoolean = "boolean"
const SfCombobox = "combobox"
const SfCurrency = "currency"
const SfDataCategoryGroupReference = "datacategorygroupreference"
const SfDate = "date"
const SfDatetime = "datetime"
const SfDouble = "double"
const SfEmail = "email"
const SfEncryptedString = "encryptedstring"
const SfId = "id"
const SfInt = "int"
const SfMultiPickList = "multipicklist"
const SfPercent = "percent"
const SfPhone = "phone"
const SfPicklist = "picklist"
const SfReference = "reference"
const SfString = "string"
const SfTextArea = "textarea"
const SfTime = "time"
const SfUrl = "url"
